title = "Sara Piscitelli"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"

[params]
address = "Rome, Italy"
email = ""
role = "AI research"
favicon = "/favicon.ico"
firstName = "Sara"
lastName = "Piscitelli"
phone = ""
profileImage = "img/avatar_profile.jpg"
showQr = false
showContact = false
showSocializations = true
sections = ["experience","education","skills","publications","creations"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/sara-piscitelli95/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/sarapiscitelli"
name = "GitHub"

[[params.handles]]
link = "https://huggingface.co/SaraPiscitelli"
name = "HuggingFace"
icon = "fa-solid fa-link"

[[params.handles]]
link = "https://dblp.org/pid/292/5857.html"
name = "dblp"
icon = "fa-brands fa-google-scholar"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
